# Generated by Django 3.1.1 on 2020-10-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
